version: '3.9'

services:
  # mongodb services
  mongo_db : 
    container_name : db_container
    image : mongo:latest
    restart : always
    ports : 
      - 27017:27017
    volumes : 
      - mongo_db:/data/db

  # nest api services
  api :
    build : .
    ports : 
      - 5000:5000
    environment : 
      PORT: 5000
      MONGODB_URI : mongodb://mongo_db:27017/eventManager
      IS_DEPLOYED_ENV: false`
      SYNCHRONIZE: true
      IS_TESTING_ENABLED: true
      JWT_SECRET : dfaljlkjklaf32423ashdfjhasdlkjfhalksdjhflak
    volumes : 
      - .:/usr/src/app
    depends_on : 
      - mongo_db

volumes:
  mongo_db: {}
  